Integrate pages into global searches
wolloda/keypirinha-notionSearcher pull request #2
Opened 2024-08-13 11:01 UTC by CallumWigg

- Replace notion logo with higher quality and png background.
- Pages now show up on global searches without needing to tab through "Notion: Find Pages".

2024-08-14 21:17 UTC, wolloda commented
Hello,

having pages show in global searches is a good idea. I think it should be optional (configurable in a [/src/notion.ini](../blob/master/src/notion.ini) file) though, I am personally inclined to `no` as a default.

2024-08-16 01:00 UTC, CallumWigg commented
Hi @wolloda, a great suggestion. I've implemented the logic as recommended in the latest commit.

2024-08-23 23:25 UTC, wolloda requested changes
Please change the defaults for the config item.

2024-08-23 23:25 UTC, wolloda commented on src/notion.py
> +        self._SEARCH_MODE = settings.get_bool("global_results", "main", True)
Defaults should be `False`.

2024-08-23 23:27 UTC, wolloda commented
Hello @CallumWigg thanks for implementing the config option.

Please make it `False` by default and mention the option in the [README](https://github.com/wolloda/keypirinha-notionSearcher/blob/main/README.md#options)

2024-08-24 13:48 UTC, merged